apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: appointment-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: swt.tillpistiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appointment-service
                port:
                  number: 8080
    - host: grafana-swt.tillpistiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  tls:
    - hosts:
        - swt.tillpistiak.com
        - grafana-swt.tillpistiak.com
      secretName: tls-secret
  ingressClassName: nginx
