apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: appointment-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: <SERVICE_HOST>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appointment-service
                port:
                  number: 8080
    - host: <GRAFANA_HOST>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  tls:
    - hosts:
        - <SERVICE_HOST>
        - <GRAFANA_HOST>
      secretName: tls-secret
  ingressClassName: nginx
