apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: appointment-service
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
    
      - job_name: 'appointment-service'
        metrics_path: /q/metrics
        static_configs:
          - targets: ['appointment-service:8080']
    
    # rule_files:
    #  - 'alert.rules.yml'
