apiVersion: v1
kind: Service
metadata:
  name: prometheus-internal-service
  namespace: appointment-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
