name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build_push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Generate public tls secret
        uses: azure/k8s-create-secret@v2
        with:
          namespace: "appointment-service"
          secret-type: "generic"
          secret-name: test
          data: '{ "key1": "${{ secrets.TLS_CERT }}" }'

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s -n appointment-service

      - name: Verify deployment
        run: kubectl rollout status deployment/appointment-service -n appointment-service  --timeout=15s
