name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build_push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Replace placeholders with tls secrets
        run: sed -i 's|<CERT>|${{ secrets.TLS_CERT }}|' $GITHUB_WORKSPACE/k8s/tls-secret.yaml && sed -i 's|<KEY>|${{ secrets.TLS_KEY }}|' $GITHUB_WORKSPACE/k8s/tls-secret.yaml

      - name: Replace placeholders for mariadb
        run: sed -i 's|<ROOT_PASSWORD>|${{ secrets.MYSQL_ROOT_PASSWORD }}|' $GITHUB_WORKSPACE/k8s/mariadb-secret.yaml && sed -i 's|<PASSWORD>|${{ secrets.MYSQL_PASSWORD }}|' $GITHUB_WORKSPACE/k8s/mariadb-secret.yaml

      - name: Replace placeholders for host
        run: sed -i 's|<GRAFANA_HOST>|${{ env.GRAFANA_HOST }}|' $GITHUB_WORKSPACE/k8s/ingress.yaml && sed -i 's|<SERVICE_HOST>|${{ env.SERVICE_HOST }}|' $GITHUB_WORKSPACE/k8s/ingress.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s -n appointment-service

      - name: Restart Deployment
        run: kubectl rollout restart deployment appointment-service -n appointment-service

      - name: Verify deployment
        run: kubectl rollout status deployment/appointment-service -n appointment-service  --timeout=15s
