name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Run JaCoCo for Code Coverage
        run: mvn verify

      - name: Check Code Coverage
        run: |
          COVERAGE=$(cat target/site/jacoco/jacoco.xml | grep "counter type=\"LINE\" covered" | sed 's/.*value="\([0-9]*\)".*/\1/')
          THRESHOLD=80
          
          if [ "$COVERAGE" -ge "$THRESHOLD" ]; then
            echo "Code coverage is above the threshold ($THRESHOLD%)"
          else
            echo "Code coverage is below the threshold ($THRESHOLD%)"
            exit 1
          fi